version: '3'
services:
  execapp:
    build:  
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: "npm run dev"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
